const mongoose = require('mongoose');
const StockBalance = require('../models/StockBalanceModule');
const Product = require('../models/ProductModule');
const StockOutItem = require('../models/StockOutItemModule');
const InventoryTransaction = require('../models/InventoryTransactionModule');

/**
 * Normalizes an expiry date to UTC midnight for the calendar date (YYYY-MM-DD 00:00:00.000Z).
 * Corrects timezone offsets (e.g. UTC+3 midnight saving as 21:00Z on previous day)
 * and 5-digit typo years (e.g. 20230 -> 2030).
 */
function normalizeExpiryDate(expiry) {
  if (!expiry) return null;
  if (typeof expiry === 'string') {
    expiry = expiry.trim();
    if (!expiry) return null;
  }

  let d;
  if (expiry instanceof Date) {
    d = new Date(expiry.getTime());
  } else if (typeof expiry === 'string') {
    // Check if DD/MM/YYYY or DD-MM-YYYY format
    if (/^\d{1,2}[\/-]\d{1,2}[\/-]\d{4,5}$/.test(expiry)) {
      const parts = expiry.split(/[\/-]/);
      let day = parseInt(parts[0], 10);
      let month = parseInt(parts[1], 10);
      let year = parseInt(parts[2], 10);
      if (year > 2100) {
        const s = String(year);
        if (s.startsWith('20') && s.length === 5) {
          year = parseInt('20' + s.slice(3), 10);
        }
      }
      return new Date(Date.UTC(year, month - 1, day, 0, 0, 0, 0));
    }
    // Check for 5-digit typo year in ISO string, e.g. "20230-06-28" or "+020230"
    let cleanStr = expiry.replace(/^\+0*/, '');
    const match5 = cleanStr.match(/^(\d{5})-(.*)/);
    if (match5) {
      const s = match5[1];
      if (s.startsWith('20')) {
        const fixedYear = '20' + s.slice(3);
        cleanStr = fixedYear + '-' + match5[2];
      }
    }
    d = new Date(cleanStr);
  } else {
    d = new Date(expiry);
  }

  if (isNaN(d.getTime())) return null;

  let year = d.getUTCFullYear();
  if (year > 2100) {
    const s = String(year);
    if (s.startsWith('20') && s.length === 5) {
      year = parseInt('20' + s.slice(3), 10);
    }
  }

  let month = d.getUTCMonth();
  let date = d.getUTCDate();

  // If hours is >= 20, it was generated by local UTC+3 midnight offset (e.g. 21:00Z of previous day)
  if (d.getUTCHours() >= 20) {
    const nextDay = new Date(Date.UTC(year, month, date + 1));
    year = nextDay.getUTCFullYear();
    month = nextDay.getUTCMonth();
    date = nextDay.getUTCDate();
  }

  return new Date(Date.UTC(year, month, date, 0, 0, 0, 0));
}

/**
 * Builds a query filter for matching an existing StockBalance batch by inventory identity:
 * - exact productId
 * - exact expiry date (calendar day range match)
 * - exact batchNumber if specified, or empty/null
 * - exact locationId if specified, or null
 */
function buildStockBalanceFilter(productId, expiry, batchNumber = "", locationId = null) {
  const normalizedExpiry = normalizeExpiryDate(expiry);
  const filter = {
    productId: new mongoose.Types.ObjectId(String(productId))
  };

  if (locationId) {
    filter.locationId = new mongoose.Types.ObjectId(String(locationId));
  } else {
    filter.locationId = { $in: [null, undefined] };
  }

  const cleanBatch = (batchNumber || "").trim();
  if (cleanBatch) {
    filter.batchNumber = cleanBatch;
  } else {
    filter.batchNumber = { $in: ["", null, undefined] };
  }

  if (normalizedExpiry) {
    const start = new Date(normalizedExpiry);
    start.setUTCHours(0, 0, 0, 0);
    const end = new Date(normalizedExpiry);
    end.setUTCHours(23, 59, 59, 999);
    filter.expiry = { $gte: start, $lte: end };
  } else {
    filter.expiry = { $in: [null, undefined] };
  }

  return filter;
}

/**
 * Finds an existing StockBalance that matches the inventory identity.
 */
async function findMatchingStockBalance(productId, expiry, batchNumber = "", locationId = null, session = null) {
  const filter = buildStockBalanceFilter(productId, expiry, batchNumber, locationId);
  let query = StockBalance.findOne(filter);
  if (session) query = query.session(session);
  return await query;
}

/**
 * Safe database consolidation:
 * Scans all StockBalances, groups by inventory identity (productId, normalized expiry, batchNumber, locationId),
 * and consolidates duplicates into ONE authoritative StockBalance record.
 * Sums quantities, preserves audit trails, repoints references, and removes duplicate records.
 */
async function consolidateAllStockBalances() {
  try {
    const balances = await StockBalance.find({}).sort({ createdAt: 1 }).lean();
    const groups = new Map();

    for (const b of balances) {
      const pId = String(b.productId);
      const normExp = normalizeExpiryDate(b.expiry);
      const expKey = normExp ? normExp.toISOString().slice(0, 10) : 'no-expiry';
      const batchKey = (b.batchNumber || '').trim();
      const key = `${pId}__${expKey}__${batchKey}`;
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key).push(b);
    }

    let consolidatedGroups = 0;
    let totalRemoved = 0;

    for (const [key, list] of groups.entries()) {
      if (list.length <= 1) continue;

      consolidatedGroups++;
      // Choose primary: prefer the one with highest quantity or earliest created
      list.sort((a, b) => (b.quantity || 0) - (a.quantity || 0));
      const primary = list[0];
      const duplicates = list.slice(1);

      const totalQuantity = list.reduce((sum, item) => sum + (Number(item.quantity) || 0), 0);
      const normExp = normalizeExpiryDate(primary.expiry || duplicates.find(d => d.expiry)?.expiry);
      const cleanBatch = (primary.batchNumber || duplicates.find(d => d.batchNumber)?.batchNumber || '').trim();

      // Update primary record
      await StockBalance.findByIdAndUpdate(primary._id, {
        $set: {
          quantity: totalQuantity,
          expiry: normExp,
          batchNumber: cleanBatch
        }
      });

      // Repoint any references in StockOutItem & InventoryTransaction to primary._id
      const duplicateIds = duplicates.map(d => d._id);
      await StockOutItem.updateMany(
        { stockBalanceId: { $in: duplicateIds } },
        { $set: { stockBalanceId: primary._id } }
      );
      await InventoryTransaction.updateMany(
        { stockBalanceId: { $in: duplicateIds } },
        { $set: { stockBalanceId: primary._id } }
      );

      // Remove duplicate StockBalance records
      await StockBalance.deleteMany({ _id: { $in: duplicateIds } });
      totalRemoved += duplicateIds.length;

      console.log(`[consolidateAllStockBalances] Consolidated group ${key}: kept ${primary._id}, merged ${duplicates.length} records. New Qty: ${totalQuantity}`);
    }

    if (consolidatedGroups > 0) {
      console.log(`[consolidateAllStockBalances] Successfully consolidated ${consolidatedGroups} duplicate groups (${totalRemoved} redundant records removed).`);
    }

    return { consolidatedGroups, totalRemoved };
  } catch (err) {
    console.error('[consolidateAllStockBalances] Error during consolidation:', err);
    return { consolidatedGroups: 0, totalRemoved: 0, error: err.message };
  }
}

module.exports = {
  normalizeExpiryDate,
  buildStockBalanceFilter,
  findMatchingStockBalance,
  consolidateAllStockBalances
};
